### ISSUE TITLE
Weird behavior regarding parameter -o/--supported

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#12]
## Issue

We observe a weird behaviour when try to pass as parameter `-o` or `--supported`. See hereafter

**Good**
```
kreate project -i fruit-client-sb -g io.cool -p io.cool.demo --supported=false -s 2.1.6.RELEASE -t client -v 1.0.0-SNAPSHOT 
Selected Spring Boot: 2.1.6.RELEASE
Selected template: client
Selected Group Id: io.cool
Selected Artifact Id: fruit-client-sb
Selected Version: 1.0.0-SNAPSHOT
Selected Package name: io.cool.demo
? Project location (immediate child directory of /Users/dabou/Code/snowdrop/kreate) 
```

**Bad**
```
kreate project -i fruit-client-sb -g io.cool -p io.cool.demo -s 2.1.6.RELEASE -t client -v 1.0.0-SNAPSHOT 
Selected Spring Boot: 2.1.6.RELEASE
? Use 2.1.6.RELEASE supported version (Y/n) 
```

When we don't pass the parameter `-o or --supported`, then a question is asked while in fact the default option which is false should be used

**Comment by metacosm** [comment]
Actually, the behavior is expected but maybe surprising. There is no way to specify a `nil` default value for a boolean flag, i.e. specify that this flag needs a user-specified value and not provide any default value. To be able to have the possibility to provide a value in interactive mode, any default value must be ignored because, otherwise, the question will never show up in interactive mode. So, if you want to not use the supported BOM in non-interactive mode, you **need** to set the `supported` flag to `false`.
